#
# Copyright 2017-2020 Martin Goellnitz.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#- name: Upgrade all packages on CentOS/RedHat
#  yum: name=* state=latest
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
 
- name: Include configuration for site
  include_vars:
    file: "../../sites/{{ site_name }}/configuration.yml"

- name: Tune MOTD
  template: src=motd.txt dest=/etc/motd

- name: Ensure some basic tools
  package:
    name:
      - net-tools
      - curl
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: mariadb.yml

- include: httpd.yml

- include: mediawiki.yml
