#
# Copyright 2020 Martin Goellnitz.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Following https://www.theurbanpenguin.com/installing-mariadb-using-ansible/
- name: Install MariaDB
  package:
    name:
      - mariadb-server
      - python3-pymysql
    state: latest

- name: Start MariaDB
  service:
    name: mariadb
    enabled: true
    state: started

# TODO:
#- name: Set local root password
#  mysql_user:
#    login_user: root
#    login_password: "{{ mariadb_root_password }}"
#    user: root
#    check_implicit_admin: true
#    password: "{{ mariadb_root_password }}"
#    host: localhost
#- name: Remove all remote root users
#  mysql_user:
#    check_implicit_admin: true
#    login_user: root
#    login_password: "{{ mariadb_root_password }}"
#    user: root
#    host: "{{ ansible_fqdn }}"
#    state: absent
